### PR TITLE
fix waveos location

### PR DESCRIPTION
**Pull request by 9xbt**
he doesn't deserve being on top of the list
also i put it at the end of the list (the end of the list at the time he made the pr) so its appropriate

### CODE REVIEW

**Comment by prescott2m** [comment]
LGTM

**Comment by AnErrupTion** [comment]
@9xbt @Winksplorer Eh, why? All places are equal on the README, and anyone can add them wherever they want, provided they're in the right category of course (which WaveOS is).

**Comment by 9xbt** [comment]
yeah but he added it to the top so more people see it, even though it should be by order of addition

**Comment by AnErrupTion** [comment]
> yeah but he added it to the top so more people see it, even though it should be by order of addition

Eh, people are free to add them even starting from the top, it doesn't really matter in my opinion.

**Pull request closed without merging**
